### PR TITLE
F#6 upl soft ch model

### PR DESCRIPTION
**Pull request by v-lavrushko**
Soft chairs: done.

### CODE REVIEW

**Review by AndriyPt — CHANGES_REQUESTED** [review]
Please remove file `robert_gazebo/cad/.DS_Store` and add `.DS_Store` to .gitignore :)

**Comment by AndriyPt** [comment]
Please restore file `robert_gazebo/worlds/ucu.world`

**Comment by v-lavrushko** [comment]
Done.

**Comment by AndriyPt** [comment]
@v-lavrushko chair is gigantic compare to robot and table. Please make it according to real measurements
image

**Comment by sofiia-tesliuk** [comment]
Done.

**Review by AndriyPt — APPROVED** [review]

**Pull request merged**
