### PR TITLE
F#1 ucu building model

### PR DESCRIPTION
**Pull request by v-lavrushko**

### CODE REVIEW

**Comment by AndriyPt** [comment]
@v-lavrushko robot is spawned upside down
image
Please fix it :)

**Comment by AndriyPt** [comment]
@v-lavrushko I have error in my console
```bash
process[spawn_husky_model-14]: started with pid [21406]
[ERROR] [1520721493.229655988, 743.613000000]: SpawnModel: Failure - model name / already exist.
[spawn_husky_model-14] process has finished cleanly
```
This is because you world file `ucu.world` has husky definition and launch file is adding husky definition as well. Please remove husky robot inclusion from `ucu.world` file.

**Comment by v-lavrushko** [comment]
Problem solved.

**Comment by AndriyPt** [comment]
@v-lavrushko everything looks good in ucu.world. Please delete the following files 
```
robert_gazebo/worlds/columns/model.config
robert_gazebo/worlds/columns/model.sdf
robert_gazebo/worlds/test
robert_gazebo/worlds/ucu_basic_frame/model.config
robert_gazebo/worlds/ucu_basic_frame/model.sdf
```
These files are not needed :)

**Review by AndriyPt — CHANGES_REQUESTED** [review]
Please fix my remarks

**Review by AndriyPt — APPROVED** [review]

**Pull request merged**
