### PR TITLE
F#56 add lights ucu world

### LINKED ISSUE #56: Black portraits instead of pictures
Please fix appearance of portraits
Currently you could not see any faces
image

### PR DESCRIPTION
**Pull request by sofiia-tesliuk**
closes #59 
closes #56

### CODE REVIEW

**Comment by AndriyPt** [comment]
Still doesn't look good 
image
Please make pictures brighter.

**Review by AndriyPt — CHANGES_REQUESTED** [review]
Quality is not good

**Comment by sofiia-tesliuk** [comment]
On my computer it looks like this:
And I have already pushed all changes.

**Comment by AndriyPt** [comment]
Bad orientation of the pictures
image

**Comment by sofiia-tesliuk** [comment]
Done.

**Review by AndriyPt — APPROVED** [review]

**Pull request merged**
