### PR TITLE
F#5 board models

### LINKED ISSUE #5: Upload models of boards
Upload blender models of standing board and simple board into robert_gazebo/cad/ directory

Upload  the visual models of standing board and simple board  in .dae extension into robert_gazebo/meshes/ directory

Upload  the collision models of standing board and simple board in .dae extension into robert_gazebo/meshes/ directory

Upload  the collision models of standing board and simple board in .sdf extension into robert_gazebo/models/ directory

Upload the collision models of the standing board and simple board in .config extension into robert_gazebo/models/ directory

### PR DESCRIPTION
**Pull request by v-lavrushko**
Board models done,
closes #5

### CODE REVIEW

**Review by AndriyPt — CHANGES_REQUESTED** [review]
Please restore file `robert_gazebo/worlds/ucu.world`

**Comment by AndriyPt** [comment]
@deathtanks Please restore file `robert_gazebo/worlds/ucu.world` and remove blend1 files

**Comment by AndriyPt** [comment]
Please restore file `robert_gazebo/worlds/ucu.world`

**Comment by LAnastasiia** [comment]
Done.

**Review by AndriyPt — APPROVED** [review]

**Pull request merged**
